  # Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Education site
email: compass@somagnetic.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://compassofdesign.com   # with the https protocol
enforce_ssl: compassofdesign.com   # without any protocol
category_dir: "categories"
category_layout: "index.html"
permalink: pretty
# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: archive/:title
collections:
  principle:
    h2: Design Principles
    h4: These books are to help understand the funtamentals of design
  strategy:
    h2: Design Strategy
    h4: Design thinking, design strategy, and help with applying the design process.
  freelance:
    h2: Freelancing and Agency work
    h4: Books to help you run your agency or freelance business with ease.
  typography:
    h2: Typography and Hand Lettering
    h4: Good type is the foundation for nearly every form of design.
  logo:
    h2: Logo Design
    h4: Books from some of the best logo designers alive and un-dead.
  branding:
    h2: Branding and Marketing
    h4: Books written to understand the entire brand experience.
  printdesign:
    h2: Print Design
    h4: Books for the best practices of designign for print.
  ui:
    h2: UI Design
    h4: Books to help understand user interaction with interface design.
  ux:
    h2: UX Design
    h4: User experience in everyday things. UX design counts for physical and digital goods.
  illustration:
    h2: Illustration
    h4: Books for applying illustration to the business world.
